apiVersion: v1
kind: Service
metadata:
  name: gke-cred-audit
  labels:
    app.kubernetes.io/name: gke-cred-audit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gke-cred-audit
  ports:
    - name: http
      port: 8787
      targetPort: 8787
      protocol: TCP
